name: Deploy backend
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: self-hosted
    environment: development
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker stop $(docker ps -q --filter ancestor=find-your-wine) || true && docker rm --force find-your-wine || true && docker rmi --force find-your-wine || true
          docker build . -t find-your-wine --progress=plain
          docker run -p 3002:3002 --name find-your-wine -d find-your-wine

  